method: fuzzy
text_col: address_norm

# benzerlik
scorer: token_set_ratio     
threshold: 60           
topk: 3

# id alanları
left_id: id
right_id: id

# bloklama: aynı bloğa düşenler birbiriyle kıyaslanır
block_by: digits+prefix6   

weights:
  text: 0.8
  digits: 0.15
  geo: 0.05
geo_max_km: 1.5            
