lowercase: true
strip_extra_spaces: true

# İngilizce yol türlerini TR'ye çevir
regex:
  - pattern: "\\bstreet\\b"
    repl: "sokak"
  - pattern: "\\bst\\.\\b"
    repl: "sokak"
  - pattern: "\\bavenue\\b"
    repl: "cadde"
  - pattern: "\\bave\\.\\b"
    repl: "cadde"

  # no:107 / no. 107 / no107 → no 107
  - pattern: "\\bno\\s*[:\\.]?\\s*(\\d+)\\b"
    repl: "no \\1"

  # fazla noktalama → boşluk
  - pattern: "\\s*[.,]+\\s*"
    repl: " "

abbreviations:
  mh: mahalle
  mah: mahalle
  cad: cadde
  cadd: cadde
  sk: sokak
