fold_chars: tr
lowercase: true
strip_punctuation: false
strip_extra_spaces: true

replace:
  " No:": " no "
  " No ": " no "

abbreviations:
  mh.: mahalle
  mah.: mahalle
  cd.: cadde
  cad.: cadde
  sk.: sokak
  sok.: sokak
  blv.: bulvar
  blvd.: bulvar

stopwords:
  - türkiye

regex:
  - { pattern: "\\bno\\s*[:=]?", repl: " no " }
  - { pattern: "\\s{2,}", repl: " " }
