lowercase: true
strip_extra_spaces: true
strip_punctuation: true   # noktalama temizliği
fold_chars: tr            # TR güvenli küçültme
abbreviations:
  sokak: sk
  cadde: cd
stopwords: ["mahallesi", "mah.", "no", "daire"]
