name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
          python -m pip install -e .
      - name: Run tests (verbose on fail)
        run: |
          python -m pytest -q || (echo "---- verbose rerun ----" && python -m pytest -vv ; exit 1)
